---
server:
  host: 0.0.0.0
  port: "8000"
  auth:
    - client_name: api
      client_key: test
database:
  type: postgres
  username: db_user
  password: password
  database: boilerplate_local
  url: localhost
  port: "5432"
aws:
  access_key: random
  aws_secret: random
  s3:
    endpoint_url: null
  sqs:
    region: us-east-1
    queue_url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/test-queue
    endpoint: http://localhost.localstack.cloud:4566
